# Generated by Django 4.1.5 on 2023-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='lat')),
                ('long', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='long')),
                ('bikes', models.IntegerField(verbose_name='bikes')),
            ],
        ),
    ]
