# Generated by Django 4.1.5 on 2023-01-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Username')),
                ('password', models.CharField(max_length=150, verbose_name='Password')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.profile')),
            ],
        ),
    ]
